services:
  - type: web
    name: body-change-ranking
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/index.cjs
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
